// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Gt_ueT9tIuKqp-3_mvenN-EpLStC_ME',
    appId: '1:890847482230:web:12be6e1b1af7621eac6a57',
    messagingSenderId: '890847482230',
    projectId: 'healthsathi-c7ec6',
    authDomain: 'healthsathi-c7ec6.firebaseapp.com',
    storageBucket: 'healthsathi-c7ec6.firebasestorage.app',
    measurementId: 'G-X7ZQRDS8MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMczFcRE790IhCTorfkZrheXxKDyliHDU',
    appId: '1:890847482230:android:7b27c46724e5fce0ac6a57',
    messagingSenderId: '890847482230',
    projectId: 'healthsathi-c7ec6',
    storageBucket: 'healthsathi-c7ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWJ3T7UMftYe1Rq5LdSOtgtM5MfL2iQGA',
    appId: '1:890847482230:ios:3dfdf32360da6d88ac6a57',
    messagingSenderId: '890847482230',
    projectId: 'healthsathi-c7ec6',
    storageBucket: 'healthsathi-c7ec6.firebasestorage.app',
    iosBundleId: 'com.example.healthsathi',
  );
}
